version: '3.4'

services:

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    networks:
      - net
    ports:
      - 1521:1521
    environment:
      - ORACLE_DATABASE=foobar
      - ORACLE_PASSWORD=yesno
      - APP_USER=foo
      - APP_USER_PASSWORD=bar

networks:
  net: